### ISSUE TITLE
Can not build with ghc 8.0.1 

### ISSUE THREAD

**Issue by cgo** [lehins/hip#3]
I am getting these errors when trying to build (in a sandbox) with ghc 8.0.1:

src/Graphics/Image/Interface.hs:127:1: error:
    • Potential superclass cycle for ‘Array’
        one of whose superclass constraints is headed by a type family:
          ‘Elt arr cs e’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘Array’

src/Graphics/Image/Interface.hs:232:1: error:
    • Potential superclass cycle for ‘ManifestArray’
        one of whose superclasses is ‘Array’
        one of whose superclass constraints is headed by a type family:
          ‘Elt arr cs e’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘ManifestArray’

src/Graphics/Image/Interface.hs:263:1: error:
    • Potential superclass cycle for ‘SequentialArray’
        one of whose superclasses is ‘ManifestArray’
        one of whose superclasses is ‘Array’
        one of whose superclass constraints is headed by a type family:
          ‘Elt arr cs e’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘SequentialArray’

src/Graphics/Image/Interface.hs:284:1: error:
    • Potential superclass cycle for ‘MutableArray’
        one of whose superclasses is ‘ManifestArray’
        one of whose superclasses is ‘Array’
        one of whose superclass constraints is headed by a type family:
          ‘Elt arr cs e’
      Use UndecidableSuperClasses to accept this
    • In the class declaration for ‘MutableArray’

**Comment by lehins** [comment]
@cgo, thank you for reporting this. I meant to add GHC 8 support a while back. Please, let me know if you still experience any issue with the library.

**Comment by cgo** [comment]
Thanks for fixing this! I'll check that out once I find some time. And thanks for making this library!
